In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df  = pd.read_csv("../data/raw/churn_dataset_messy.csv")
df.head()

,ID,CustomerID,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,RegistrationDate,SatisfactionScore,NumComplaints,Email,Exited
0,111819,82197283105,Johnson,567.0,Germany,Homme,38,8.0,5234.53,2.0,1,1,0,2021-11-05,4,0.0,diane30@example.net,1
1,101210,36912803096,Lawrence,894.0,Spain,Male,54,3.0,13629.78,3.0,1,0,113027.18,2011-05-26,4,0.0,gordonosullivan@example.com,0
2,109466,97155583156,Chevalier,788.0,Spain,Male,40,9.0,17123.43,1.0,1,0,96117.51,2020-11-27,2,0.0,monniersylvie@example.org,0
3,104337,26159789757,Mülichen,608.0,Spain,Male,36,9.0,128278.02,1.0,1,1,81814.93,2015-10-28,4,2.0,derekstewart@example.org,0
4,112467,54492422739,Thomas,714.0,France,Male,25,1.0,7729.62,1.0,0,1,41672.29,2019-01-08,4,0.0,email@,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15750 entries, 0 to 15749
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 15750 non-null  int64
 1   CustomerID         15750 non-null  int64
 2   Surname            15658 non-null  object
 3   CreditScore        15415 non-null  float64
 4   Geography          15594 non-null  object
 5   Gender             15589 non-null  object
 6   Age                15270 non-null  object
 7   Tenure             15288 non-null  float64
 8   Balance            15321 non-null  object
 9   NumOfProducts      15426 non-null  float64
 10  HasCrCard          15442 non-null  object
 11  IsActiveMember     15266 non-null  object
 12  EstimatedSalary    15333 non-null  object
 13  RegistrationDate   15412 non-null  object
 14  SatisfactionScore  15150 non-null  object
 15  NumComplaints      15270 non-null  float64
 16  Email              15240 non-null  object
 17  Exited             15750 non-null  int64
dtypes: float64(4), int64(3), object(11)
memory usage: 2.2+ MB

In [5]:
df.describe().round(2)

,ID,CustomerID,CreditScore,Tenure,NumOfProducts,NumComplaints,Exited
count,15750.00,1.575000e+04,15415.00,15288.00,15426.00,15270.00,15750.00
mean,107505.14,5.035600e+10,652.45,6.01,1.77,11.26,0.26
std,4321.95,2.891970e+10,128.52,10.35,1.04,101.01,0.44
min,100000.00,1.219329e+07,-50.00,-1.00,-1.00,-1.00,0.00
25%,103773.25,2.514456e+10,582.00,2.00,1.00,0.00,0.00
50%,107501.50,5.060873e+10,651.00,5.00,2.00,0.00,0.00
75%,111254.75,7.527190e+10,719.00,8.00,2.00,1.00,1.00
max,114999.00,9.999214e+10,1500.00,100.00,10.00,999.00,1.00

In [14]:
df.describe(include="object")

,Surname,Geography,Gender,Age,Balance,HasCrCard,IsActiveMember,EstimatedSalary,RegistrationDate,SatisfactionScore,Email
count,15658,15594,15589,15270,15321,15442,15266,15333,15412,15150,15240
unique,2358,9,11,112,14450,9,6,14305,5045,13,13971
top,Smith,Germany,Male,42,-99999.99,1,1,-500,date inconnue,3,email@
freq,119,4892,8659,518,86,7247,7324,82,165,2829,309

In [7]:
df.dtypes

ID                     int64
CustomerID             int64
Surname               object
CreditScore          float64
Geography             object
Gender                object
Age                   object
Tenure               float64
Balance               object
NumOfProducts        float64
HasCrCard             object
IsActiveMember        object
EstimatedSalary       object
RegistrationDate      object
SatisfactionScore     object
NumComplaints        float64
Email                 object
Exited                 int64
dtype: object

In [8]:
df.shape

(15750, 18)

In [9]:
df.isna().sum()

ID                     0
CustomerID             0
Surname               92
CreditScore          335
Geography            156
Gender               161
Age                  480
Tenure               462
Balance              429
NumOfProducts        324
HasCrCard            308
IsActiveMember       484
EstimatedSalary      417
RegistrationDate     338
SatisfactionScore    600
NumComplaints        480
Email                510
Exited                 0
dtype: int64

In [10]:
(df.isna().sum()/len(df)*100).round(2).to_frame("% valeurs manquantes")

                   % valeurs manquantes
ID                                 0.00
CustomerID                         0.00
Surname                            0.58
CreditScore                        2.13
Geography                          0.99
Gender                             1.02
Age                                3.05
Tenure                             2.93
Balance                            2.72
NumOfProducts                      2.06
HasCrCard                          1.96
IsActiveMember                     3.07
EstimatedSalary                    2.65
RegistrationDate                   2.15
SatisfactionScore                  3.81
NumComplaints                      3.05
Email                              3.24
Exited                             0.00

In [12]:
df.duplicated().sum()

np.int64(750)

In [13]:
df.nunique()

ID                   15000
CustomerID           15000
Surname               2358
CreditScore            611
Geography                9
Gender                  11
Age                    112
Tenure                  13
Balance              14450
NumOfProducts            7
HasCrCard                9
IsActiveMember           6
EstimatedSalary      14305
RegistrationDate      5045
SatisfactionScore       13
NumComplaints            8
Email                13971
Exited                   2
dtype: int64